// src/surveys/v3/sections/01_org_structure.ts
import type { Section } from '../types';

// Общий набор опций (Да/Нет/НП); НП (weight=0) учитывается как выполнено в computeMaturity
const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_01_ORG_STRUCTURE: Section = {
  key: 'org_structure',
  title: 'Организационная структура',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 1,
  questions: [
    // Уровень 1
    {
      id: 's01.org.l1.q1',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l1',
      level: 1,
      text: 'Назначен ответственный за ИБ, имеющий трудовые отношения с компанией (как минимум выполняет роль по совместительству, может быть назначен специалист, не имеющий руководящего опыта).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l1.q2',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l1',
      level: 1,
      text: 'Определён круг обязанностей ответственного за ИБ, например, в трудовом договоре и/или должностной инструкции.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's01.org.l2.q1',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l2',
      level: 2,
      text: 'Создана роль CISO (руководитель подразделения кибербезопасности), документально определены обязанности CISO.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l2.q2',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l2',
      level: 2,
      text: 'Руководитель подразделения кибербезопасности (CISO) подчиняется непосредственно руководителю компании (CEO).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l2.q3',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l2',
      level: 2,
      text: 'Для работников, ответственных за обеспечение ИБ, документально определены должностные обязанности и ответственность за их исполнение. С должностными обязанностями ознакомлены под подпись все работники, ответственные за обеспечение ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l2.q4',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l2',
      level: 2,
      text: 'Распределена ответственность за обеспечение ИБ по всем направлениям, включая обеспечение ИБ при работе с третьими сторонами.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l2.q5',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l2',
      level: 2,
      text: 'Внедрена матрица кадровых решений за нарушения в области ИБ, обеспечено применение дисциплинарных взысканий за нарушение требований ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's01.org.l3.q1',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l3',
      level: 3,
      text: 'Создано самостоятельное структурное подразделение, ответственное за обеспечение ИБ, определены его функции и задачи.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l3.q2',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l3',
      level: 3,
      text: 'Организационно-штатная структура подразделения ИБ сформирована с учётом направлений деятельности компании, модели угроз компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l3.q3',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l3',
      level: 3,
      text: 'Определена ответственность и обязанности всех подразделений компании в части соблюдения требований ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's01.org.l4.q1',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l4',
      level: 4,
      text: 'CISO имеет полномочия принимать решения об отключении ИТ-сервисов (в том числе — влияющих на бизнес-процессы) после уведомления владельцев бизнес-процессов. Соответствующие полномочия документально определены. CISO имеет право вето при согласовании новых или модификации существующих информационных потоков, АС, сервисов. Для контроля подразделение ИБ включено в соответствующие процессы компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l4.q2',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l4',
      level: 4,
      text: 'CISO взаимодействует с руководителями бизнес-подразделений компании, поддерживая взаимную осведомленность. Обеспечено понимание подразделением ИБ бизнес-процессов, а также понимание бизнесом задач, функций и процессов ИБ компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l4.q3',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l4',
      level: 4,
      text: 'Штатная численность подразделения ИБ планируется долгосрочно, с учётом стратегии бизнеса, стратегий ИТ и ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l4.q4',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l4',
      level: 4,
      text: 'В компании утверждена матрица компетенций ИБ для работников, ролей в подразделении ИБ. Для работников, не соответствующих требованиям, планируется и реализуется обучение и/или применяются кадровые решения.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's01.org.l5.q1',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l5',
      level: 5,
      text: 'Подразделение ИБ участвует в разработке и обновлении корпоративной стратегии и стратегии развития ИТ компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's01.org.l5.q2',
      sectionKey: 'org_structure',
      categoryKey: 'org_structure.l5',
      level: 5,
      text: 'CISO обладает полномочиями на отключение любых ИТ-сервисов без согласования с владельцами бизнес-процессов, в том числе сервисов, влияющих на бизнес-процессы компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_01_ORG_STRUCTURE;
