// src/surveys/v3/sections/02_it_asset_mgmt.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_02_IT_ASSET_MGMT: Section = {
  key: 'it_asset_mgmt',
  title: 'Управление ИТ-активами',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 2,
  questions: [
    // Уровень 1
    {
      id: 's02.itam.l1.q1',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l1',
      level: 1,
      text: 'Ведётся реестр АРМ, в том числе виртуальных, при этом определены правила наименования АРМ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l1.q2',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l1',
      level: 1,
      text: 'Ведётся реестр серверов, в том числе виртуальных, при этом определены правила наименования серверов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l1.q3',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l1',
      level: 1,
      text: 'Ведётся реестр сетевого оборудования, в том числе виртуального, при этом определены правила наименования сетевого оборудования.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l1.q4',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l1',
      level: 1,
      text: 'Установка ПО осуществляется из определённых источников дистрибутивов ПО для всех АРМ, серверов и сетевых устройств. Перечень источников управляется, согласовывается с подразделением ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l1.q5',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l1',
      level: 1,
      text: 'Средствами автоматизации обеспечена возможность сбора сведений об установленном ПО для всех АРМ и серверов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l1.q6',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l1',
      level: 1,
      text: 'Определены ИТ-администраторы для каждого ИТ-актива: конкретные работники или группа администрирования ИТ-актива.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's02.itam.l2.q1',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l2',
      level: 2,
      text: 'В компании используется автоматизированное решение для ведения реестра ИТ-активов. Реестры ИТ-активов для сетевого оборудования, АРМ, серверов, иного оборудования, подключаемого к сети, содержат следующую информацию: 1) имя устройства (hostname); 2) физический адрес размещения устройства; 3) IP-адреса, присвоенные устройству; 4) идентификатор устройства (серийный/инвентарный номер); 5) статус эксплуатации; 6) ИТ-администратор актива; владелец ИТ-актива; URL (если применимо); 7) доступность из сети интернет; 8) критичность ИТ-актива.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l2.q2',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l2',
      level: 2,
      text: 'Используются инструменты актуализации реестра ИТ-активов (автоматизированные — для АРМ и серверов, а для сетевого оборудования допускается обогащение реестра в ручном режиме).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l2.q3',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l2',
      level: 2,
      text: 'Разработан и внедрён перечень разрешённого и/или запрещённого ПО, изменение перечней согласовывается с подразделением ИБ. Формализованы процессы установки ПО и управления исключениями.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's02.itam.l3.q1',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l3',
      level: 3,
      text: 'Процесс управления ИТ-активами регламентирован. Определены этапы жизненного цикла ИТ-активов, точки контроля ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l3.q2',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l3',
      level: 3,
      text: 'Для управления всеми ИТ-активами применяется централизованное решение класса CMDB. Изменение информации об ИТ-активах, включая их связи с другими ИТ-активами, отражается в CMDB.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's02.itam.l3.q3',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l3',
      level: 3,
      text: 'Проводится регулярная (не реже 1 раза в год) полная инвентаризация ИТ-активов с целью выявления некорректных или неактуальных данных.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's02.itam.l4.q1',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l4',
      level: 4,
      text: 'Система CMDB интегрирована с автоматизированными инструментами для выявления 100% ИТ-активов компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's02.itam.l5.q1',
      sectionKey: 'it_asset_mgmt',
      categoryKey: 'it_asset_mgmt.l5',
      level: 5,
      text: 'Все типы ИТ-активов компании контролируются в CMDB, для каждого актива заполнен полный набор полей. CMDB содержит актуальные данные по всем типам ИТ-активов. Данные в CMDB обновляются в режиме реального времени, отклонения процесса анализируются, планируются и реализуются корректирующие мероприятия.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_02_IT_ASSET_MGMT;
