// src/surveys/v3/sections/03_risk_based.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_03_RISK_BASED: Section = {
  key: 'risk_based',
  title: 'Риск-ориентированный подход',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 3,
  questions: [
    // Уровень 1
    {
      id: 's03.risk.l1.q1',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l1',
      level: 1,
      text: 'Определены актуальные угрозы ИБ для компании, как минимум в виде рабочих документов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l1.q2',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l1',
      level: 1,
      text: 'Определены работники ИБ, ответственные за выявление актуальных угроз и рисков ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's03.risk.l2.q1',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l2',
      level: 2,
      text: 'Разработана и утверждена общая модель угроз и нарушителя ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l2.q2',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l2',
      level: 2,
      text: 'Проводится регулярная (не реже 1 раза в год) оценка рисков ИБ для компании (возможно, используется экспертная оценка), методика экспертной оценки рисков ИБ разработана и утверждена.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l2.q3',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l2',
      level: 2,
      text: 'Выявленные риски ИБ регистрируются в едином реестре рисков, описываются митигирующие меры, условия пересмотра и владелец риска. Руководитель компании информируется о выявленных рисках.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l2.q4',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l2',
      level: 2,
      text: 'Для выявленных рисков ИБ (как минимум для наиболее критичных) назначаются владельцы. Определены функции и обязанности владельцев рисков, возможно, неформально.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's03.risk.l3.q1',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l3',
      level: 3,
      text: 'Процесс управления рисками ИБ полностью регламентирован. Определены функции и обязанности владельцев рисков ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l3.q2',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l3',
      level: 3,
      text: 'Разработаны частные модели угроз для критичных АС и сервисов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l3.q3',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l3',
      level: 3,
      text: 'Разработана и используется методика качественной/количественной оценки рисков ИБ, учитывающая определение вероятности реализации риска ИБ и возможное влияние от реализации события.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l3.q4',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l3',
      level: 3,
      text: 'Обработка рисков ИБ производится в соответствии с параметрами, зафиксированными в реестре рисков. Отклонения фиксируются, по ним принимаются и документально оформляются решения.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's03.risk.l4.q1',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l4',
      level: 4,
      text: 'Управление рисками ИБ интегрировано в корпоративную систему управления рисками.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l4.q2',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l4',
      level: 4,
      text: 'Создан коллегиальный орган для рассмотрения вопросов и принятия решений по управлению рисками ИБ, обеспечивающий баланс между развитием бизнеса и достаточным уровнем ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l4.q3',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l4',
      level: 4,
      text: 'Установлен аппетит к рискам ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's03.risk.l5.q1',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l5',
      level: 5,
      text: 'Разработана и внедрена методика проведения сценарного анализа риска ИБ для оценки возможных последствий от реализации потенциальных событий риска ИБ, методика разработки и мониторинга ключевых индикаторов риска ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's03.risk.l5.q2',
      sectionKey: 'risk_based',
      categoryKey: 'risk_based.l5',
      level: 5,
      text: 'Внедрена и используется система GRC, интегрированная с решением для управления ИТ-активами. Выявленные риски ИБ регистрируются с учётом взаимосвязи с конкретными ИТ-активами, уязвимостями в ИТ-активах. Риск ИБ отслеживается в режиме реального времени с учётом изменений в ИТ-активах.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_03_RISK_BASED;
