// src/surveys/v3/sections/06_reporting_metrics.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_06_REPORTING_METRICS: Section = {
  key: 'reporting_metrics',
  title: 'Отчётность и метрики',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 6,
  questions: [
    // Уровень 1
    {
      id: 's06.rm.l1.q1',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l1',
      level: 1,
      text: 'Отчётность по ИБ предоставляется руководству компании — по запросу, по отдельным проектам, по инцидентам ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's06.rm.l2.q1',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l2',
      level: 2,
      text: 'Обеспечено регулярное (не реже 1 раза в квартал) предоставление отчетности по ИБ руководству компании: как минимум по инцидентам ИБ, ключевым проектам ИБ, выполнению плана развития ИБ, а также по выполнению KPI (ключевого показателя эффективности) в области ИБ, установленного для CEO советом директоров компании (или эквивалентным ему высшим коллегиальным органом управления).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l2.q2',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l2',
      level: 2,
      text: 'В состав показателей эффективности деятельности руководителя компании входит ключевой показатель эффективности по ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l2.q3',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l2',
      level: 2,
      text: 'Определены ключевые показатели эффективности для руководителя подразделения ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l2.q4',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l2',
      level: 2,
      text: 'Используются метрики для оценки покрытия техническими средствами и контролями ИБ инфраструктуры/работников компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l2.q5',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l2',
      level: 2,
      text: 'Используются метрики для оценки обучения, повышения осведомлённости ИБ работников компании (в т. ч. связанные с проведением киберучений).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's06.rm.l3.q1',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l3',
      level: 3,
      text: 'Используются метрики для оценки эффективности процессов ИБ (возможно, не всех), расчёт метрик регламентирован.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l3.q2',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l3',
      level: 3,
      text: 'Метрики для процессов ИБ включаются в регулярную отчётность для руководства компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l3.q3',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l3',
      level: 3,
      text: 'Используются показатели эффективности для CISO, индивидуальные цели, показатели эффективности формируются руководством компании с учётом плана развития ИБ (как минимум — ежеквартальные цели, показатели). CISO выполняет защиту индивидуальных целей.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's06.rm.l4.q1',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l4',
      level: 4,
      text: 'Используются метрики оценки эффективности для всех процессов ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l4.q2',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l4',
      level: 4,
      text: 'Внедрены средства автоматизации расчёта метрик и визуализации отчётности по ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l4.q3',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l4',
      level: 4,
      text: 'Используются показатели эффективности для всех работников подразделения ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's06.rm.l4.q4',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l4',
      level: 4,
      text: 'Внедрены средства автоматизации для расчёта показателей эффективности подразделения ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's06.rm.l5.q1',
      sectionKey: 'reporting_metrics',
      categoryKey: 'reporting_metrics.l5',
      level: 5,
      text: 'Сформирован единый дашборд для высшего руководства, он отражает эффективность работы подразделения ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_06_REPORTING_METRICS;
