// src/surveys/v3/sections/08_access_mgmt.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_08_ACCESS_MGMT: Section = {
  key: 'access_mgmt',
  title: 'Управление доступом',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 8,
  questions: [
    // Уровень 1
    {
      id: 's08.acc.l1.q1',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l1',
      level: 1,
      text: 'Предъявляются требования к парольной защите (требования сформулированы, как минимум, в виде рабочих документов).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l1.q2',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l1',
      level: 1,
      text: 'Осуществляется контроль доступа к АС (согласование предоставления доступа подразделением ИБ) как минимум для отдельных систем.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l1.q3',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l1',
      level: 1,
      text: 'Контролируется использование непривилегированными пользователями административных прав в системах.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l1.q4',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l1',
      level: 1,
      text: 'Используются системы централизованного управления учётными записями (создание, изменение, блокирование, восстановление учётных записей) для АРМ, например, служба каталогов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's08.acc.l2.q1',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Определена парольная политика. Настройки систем компании сконфигурированы в соответствии с требованиями парольной политики.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q2',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Разработана политика управления доступом. Определена процедура согласования доступов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q3',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Разработана политика управления привилегированными учётными записями. Определены требования к защите учётных записей и согласованию привилегированного доступа.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q4',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Назначены ответственные за процесс предоставления доступов (создание, изменение, блокирование, восстановление учётных записей).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q5',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Внедрена автоматизированная система для согласования заявок на доступы.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q6',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Внедрён процесс блокирования учётных записей уволенных работников, а также работников, отсутствующих длительное время.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q7',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Используются системы централизованного управления учётными записями (создание, изменение, блокирование, восстановление) для серверных платформ (например, служба каталогов).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q8',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Разработаны ролевые модели доступа для критичных АС компании. Ролевые модели используются при согласовании доступов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l2.q9',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l2',
      level: 2,
      text: 'Внедрены процедуры контроля удалённого доступа. Производится согласование удалённого доступа и контроль подключений.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's08.acc.l3.q1',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Внедрены процедуры аудита привилегированных учётных записей на предмет актуальности и легитимности прав (проводится не реже 1 раза в квартал).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l3.q2',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Внедрена система централизованного хранения и управления учётными записями для сетевого оборудования.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l3.q3',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Внедрена система многофакторной аутентификации (2FA) при использовании привилегированных учётных записей.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l3.q4',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Внедрён выделенный изолированный шлюз (сервер для доступа к ИТ-инфраструктуре компании из сети интернет с расширенными политиками безопасности и мониторинга) для доступа подрядчиков/партнёров и иных третьих сторон.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l3.q5',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Осуществляется регулярный пересмотр ролевых моделей доступа совместно с владельцами систем (как минимум ежегодно).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l3.q6',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Внедрена система управления жизненным циклом учётных записей (IDM, как минимум, ведёт создание, изменение, учёт, блокировку УЗ и контроль прав доступа). Покрытие не менее 50% учётных записей и систем.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l3.q7',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Внедрена автоматизированная система контроля за действиями привилегированных пользователей, например, PAM-система. Обеспечено ограничение по исполняемым командам, журналирование и ограничение доступа к учётными данным (как минимум, для критичных систем).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l3.q8',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l3',
      level: 3,
      text: 'Разработаны ролевые модели доступа для АС компании. Ролевые модели используются при согласовании доступов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's08.acc.l4.q1',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l4',
      level: 4,
      text: 'Внедрена система управления жизненным циклом учётных записей (например, IDM-система). Покрытие не менее 90% учётных записей и систем.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l4.q2',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l4',
      level: 4,
      text: 'Внедрена автоматизированная система контроля за действиями привилегированных пользователей (PAM), обеспечено полное покрытие всех серверов и АС.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's08.acc.l4.q3',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l4',
      level: 4,
      text: 'Внедрены процедуры аудита пользовательских учётных записей на предмет актуальности и легитимности прав (не реже 1 раза в квартал), соответствия фактических доступов заявленным, а также фактических полномочий ролевым моделям.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's08.acc.l5.q1',
      sectionKey: 'access_mgmt',
      categoryKey: 'access_mgmt.l5',
      level: 5,
      text: 'Полностью реализована трехуровневая система учётных записей для администрирования ИТ-инфраструктуры (разные учётные записи для разных типов систем). Внедрены и автоматизированы (возможно частично) процессы выявления конфликта полномочий (SoD).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_08_ACCESS_MGMT;
