// src/surveys/v3/sections/09_network_security.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_09_NETWORK_SECURITY: Section = {
  key: 'network_security',
  title: 'Сетевая безопасность',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 9,
  questions: [
    // Уровень 1
    {
      id: 's09.net.l1.q1',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Используются средства защиты периметра сети (как минимум, с функционалом МСЭ), настроенные по принципу white-list. Выполняется контроль избыточных сетевых доступов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q2',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Используются средства защиты почтового трафика от вирусов и спама.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q3',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Сеть сегментирована по функциональному признаку. Например: DMZ, сегмент разработки, сегмент тестирования, промышленный сегмент, пользовательский сегмент, сегмент управления, гостевой сегмент.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q4',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Используются средства защиты удалённого доступа, как минимум, VPN с возможностью идентификации, аутентификации и шифрования данных.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q5',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Обеспечена защита от DDoS-атак на инфраструктуру, как минимум, настроены лимиты на периметровых средствах защиты сети.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q6',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Выполнена конфигурация взаимной аутентификации на почтовых серверах (DKIM/DMARC/SPF).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q7',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Заблокирована отправка и получение неразрешённых типов файлов во вложениях.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q8',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Администрирование инфраструктуры осуществляется из выделенной защищённой сети/сегмента сети.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l1.q9',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l1',
      level: 1,
      text: 'Критичные web-приложения/сайты защищены МСЭ для защиты веб-приложений (WAF), решение покрывает OWASP TOP-10 в режиме блокировки, есть возможность формирования индивидуальных правил.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's09.net.l2.q1',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Для защиты периметра сети используются средства класса NGFW/UTM, как минимум, функционал потокового антивируса, IDS/IPS, регулярного обновления БД сигнатур, контроля сетевых приложений на уровне L7 модели OSI.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q2',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Произведена сегментация сети на уровне отдельных сервисов. Используются правила доступа между сервисами и группами сервисов. Межсетевые правила взаимодействия составляются по принципам минимизации полномочий и запрещения всего, что явно не разрешено (default to deny).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q3',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Гостевая беспроводная сеть отделена от корпоративной сети.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q4',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Используется комплексное решение для защиты от DDoS-атак на инфраструктуру и приложения (L3/L4 и L7).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q5',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Применяется многофакторная аутентификация для всех подключений удалённого доступа.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q6',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Используются средства контроля доступа к корпоративной сети для проводных, беспроводных и удалённых подключений, например, реализация протокола 801х (возможно, контролируется только часть подключений).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q7',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Производится сбор и анализ журналов событий со средств защиты сети в SIEM/SOC.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q8',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Пользовательский доступ в интернет осуществляется исключительно через узел фильтрации веб-трафика (web proxy) с функцией TLS/SSL inspection. Правила фильтрации обновляются автоматически. Фильтрация — по категории, репутации домена или с помощью чёрных списков адресов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q9',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Веб-трафик всех серверов с сетью интернет проходит исключительно через узел фильтрации веб-трафика (web proxy) с функцией TLS/SSL inspection (возможно, правила обновляются вручную).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l2.q10',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l2',
      level: 2,
      text: 'Производится безопасная конфигурация беспроводных точек доступа/контроллеров беспроводной сети, включающая в себя: настройку безопасных протоколов (не ниже WPA2-PSK) и криптостойких алгоритмов; настройку изоляции клиентов беспроводной сети; отключение/блокировку небезопасных протоколов управления; осуществление сканирования беспроводной сети на предмет выявление фишинговых точек доступа; ограничение зоны покрытия радиовещания.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's09.net.l3.q1',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l3',
      level: 3,
      text: 'Требования к сетевой безопасности регламентированы и учитывают, как минимум, требования к: защите периметра (внешнего и внутреннего); сегментации сети (включая критерии сегментации); беспроводным сетям; управлению доступом к корпоративной сети; удалённому доступу.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l3.q2',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l3',
      level: 3,
      text: 'Используется система централизованного управления конфигурациями сетевых устройств (подключено не менее 90% сетевых устройств).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l3.q3',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l3',
      level: 3,
      text: 'Для всех удалённых подключений к сети компании производится проверка соответствия политикам безопасности, как минимум, в отношении АВПО, обновления ОС, и, если применимо, проверки статуса устройства в домене, агента DLP при доступе к сети и агента EDR. Неавторизованные или не соответствующие политикам устройства перенаправляются в изолированную сеть или блокируются.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l3.q4',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l3',
      level: 3,
      text: 'Используется решение класса «песочница» для входящего трафика, в том числе почтового (как минимум, потоковое решение, без возможности ручного управления).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's09.net.l4.q1',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l4',
      level: 4,
      text: 'Контроль межсегментного взаимодействия производится на уровне NGFW (возможно, применяется не весь функционал NGFW).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l4.q2',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l4',
      level: 4,
      text: 'Используется решение класса «песочница» с возможностью ручного выноса вердиктов и ручной загрузкой файлов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's09.net.l5.q1',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l5',
      level: 5,
      text: 'Используются инструменты для анализа аномалий в сетевом трафике (NTA), выявления скрытых и сложных атак.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's09.net.l5.q2',
      sectionKey: 'network_security',
      categoryKey: 'network_security.l5',
      level: 5,
      text: 'Инструменты для анализа сетевого трафика (NTA) интегрированы с системами мониторинга и реагирования на события ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_09_NETWORK_SECURITY;
