// src/surveys/v3/sections/10_endpoint_security.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_10_ENDPOINT_SECURITY: Section = {
  key: 'endpoint_security',
  title: 'Безопасность конечных устройств',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 10,
  questions: [
    // Уровень 1
    {
      id: 's10.endp.l1.q1',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Конфигурирование АРМ производится с учётом базовых требований ИБ (требования ИБ по безопасному конфигурированию АРМ могут быть в виде рабочих документов): отключены/удалены неиспользуемые сервисы, протоколы и модули; изменены или заблокированы все встроенные учётные записи, включая административные; изменены пароли, назначенные (по умолчанию) производителем; для пользователей ограничен доступ к BIOS и загрузчикам ОС.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q2',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Конфигурирование серверов производится с учётом базовых требований ИБ (требования ИБ по безопасному конфигурированию серверов должны существовать как минимум в виде рабочих документов): отключены/удалены неиспользуемые сервисы, протоколы и модули; изменены или заблокированы все встроенные учётные записи, включая административные; изменены пароли, назначенные (по умолчанию) производителем; для пользователей ограничен доступ к BIOS и загрузчикам ОС.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q3',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Конфигурирование корпоративных мобильных устройств производится с учётом базовых требований ИБ (требования ИБ по безопасному конфигурированию мобильных устройств должны существовать как минимум в виде рабочих документов): отключены/удалены неиспользуемые сервисы и ПО; заблокирована возможность установки приложений из недоверенных источников; установлен пароль для аутентификации на устройстве; устройство обновлено до актуальной или предыдущей версии, не имеющей критических уязвимостей.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q4',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Конфигурирование микросервисной архитектуры производится с учётом базовых требований ИБ (требования ИБ по безопасному конфигурированию микросервисной инфраструктуры могут быть в виде рабочих документов): контейнеры запускаются с минимально необходимыми привилегиями; используются доверенные образы (источники для образов); настроены и контролируются сетевые взаимодействия в микросервисной инфраструктуре.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q5',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Конфигурирование сетевого оборудования производится с учётом базовых требований ИБ (требования ИБ по безопасному конфигурированию сетевого оборудования могут быть в виде рабочих документов или используются готовые решения): изменены или заблокированы встроенные учётные записи, включая административные; изменены пароли, назначенные (по умолчанию) производителем; отключены неиспользуемые модули и протоколы; настроены безопасные протоколы администрирования.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q6',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Конфигурации безопасности для серверов централизованно управляются (например, при помощи доменных политик).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q7',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Конфигурации безопасности для АРМ централизованно управляются (например, при помощи доменных политик).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q8',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Используется АВПО для защиты рабочих станций (покрытие не менее 90%).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q9',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Используется АВПО для защиты серверов под управлением ОС Windows (покрытие не менее 90%).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q10',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Осуществляется централизованное управление АВПО и централизованное обновление баз АВПО.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l1.q11',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l1',
      level: 1,
      text: 'Прямой доступ в ИТ-инфраструктуру с личных устройств (BYOD) запрещён. Запрет реализован техническими мерами.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's10.endp.l2.q1',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Разработаны и доведены до ответственных подразделений инструкции по безопасному конфигурированию устройств (возможно, не учитывают отдельные платформы). Инструкции разработаны с использованием, как минимум, рекомендаций вендоров.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q2',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Для подготовки АРМ и серверов используется система хранения и применения базовых (золотых) образов, преднастроенных с учётом требований ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q3',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Обеспечено полное покрытие АРМ и серверов (под управлением ОС Windows) АВПО. Отклонения отслеживаются и управляются.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q4',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Осуществляется контроль обновлений баз АВПО. Отклонения отслеживаются и управляются.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q5',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Используются локальные хостовые МСЭ для АРМ и серверов. Обеспечено полное покрытие.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q6',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Используется решение класса MDM, как минимум, геолокация устройства, возможность блокировки/очистки устройства и удалённое применение политик безопасности для контроля мобильных устройств (покрытие не менее 90%).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q7',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Используется полнодисковое шифрование АРМ пользователей (выбор АРМ осуществляется на основании риск-ориентированного подхода).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q8',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Доступ в инфраструктуру с личных устройств (BYOD) осуществляется через выделенный шлюз (VDI, jump host). Настроены расширенные политики безопасности (как минимум: мониторинг, блокировка буфера обмена и проброса портов).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q9',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Используется АВПО для защиты серверов под управлением ОС *nix (покрытие не менее 90%).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q10',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Используются решения класса EDR/XDR (как минимум, сбор телеметрических данных хоста, реагирование на триггеры по результатам анализа телеметрии, возможность удалённого подключения для управления хостом) для защиты АРМ и серверов. Обеспечено полное покрытие. Отклонения выявляются и управляются.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l2.q11',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l2',
      level: 2,
      text: 'Решение EDR/XDR интегрировано с системой анализа и корреляции событий ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's10.endp.l3.q1',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l3',
      level: 3,
      text: 'Разработаны и внедрены стандарты безопасного конфигурирования для всех применяемых в компании платформ, включая АРМ, серверы, мобильные устройства, сетевое оборудования и т. п. Требования учитывают функциональное назначение и критичность конечных устройств.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's10.endp.l4.q1',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l4',
      level: 4,
      text: 'Производится регулярный пересмотр (не реже 1 раза в полгода) требований ИБ к безопасности конечных устройств.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's10.endp.l4.q2',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l4',
      level: 4,
      text: 'Золотые образы ОС регулярно актуализируются. В рамках актуализации осуществляется сканирование образов на наличие уязвимостей и соответствия требованиям безопасной конфигурации.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's10.endp.l5.q1',
      sectionKey: 'endpoint_security',
      categoryKey: 'endpoint_security.l5',
      level: 5,
      text: 'Золотые образы используются для всех новых развертываний ОС. Отклонения от конфигураций золотого образа фиксируются и управляются.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_10_ENDPOINT_SECURITY;
