// src/surveys/v3/sections/11_data_security.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_11_DATA_SECURITY: Section = {
  key: 'data_security',
  title: 'Безопасность данных',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 11,
  questions: [
    // Уровень 1
    {
      id: 's11.data.l1.q1',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l1',
      level: 1,
      text: 'Определён состав защищаемой информации, определены места и способы её хранения.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l1.q2',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l1',
      level: 1,
      text: 'Предъявляются и применяются требования ИБ к защите данных при передаче за пределы периметра компании (например, в рамках договорных отношений, соглашений о неразглашении и т. п.).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l1.q3',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l1',
      level: 1,
      text: 'Осуществляется защита каналов связи и носителей при передаче информации ограниченного доступа за пределы периметра компании (шифрование носителей и каналов, двухсторонний TLS и т. п.).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l1.q4',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l1',
      level: 1,
      text: 'Производится резервное копирование систем и информации, как минимум, ключевых активов, необходимость определяется экспертно.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's11.data.l2.q1',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l2',
      level: 2,
      text: 'Определены категории информации ограниченного доступа в зависимости от состава и критичности.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l2.q2',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l2',
      level: 2,
      text: 'Для критичных АС определены категории и состав обрабатываемой информации. Определены владельцы данных в разрезе АС.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l2.q3',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l2',
      level: 2,
      text: 'Для мониторинга доступа к критичным данным используются автоматизированные решения (например, встроенные решения или DAG).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l2.q4',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l2',
      level: 2,
      text: 'Использование съёмных носителей контролируется с использованием СЗИ и/или штатного функционала ОС.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l2.q5',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l2',
      level: 2,
      text: 'Используются решения класса DLP в режиме мониторинга, как минимум, для почтового трафика, веб-приложений, записи на съёмные носители, сетевых папок и печати. Покрытие не менее 25% пользователей, выбор контролируемых пользователей осуществляется на основании риск-ориентированного подхода.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l2.q6',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l2',
      level: 2,
      text: 'Для резервного копирования информации используется централизованное решение. Резервное копирование планируется и выполняется с учётом критичности систем и информации в них, оценки возможного влияния на бизнес компании в случае полной потери информации и/или длительного простоя систем.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l2.q7',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l2',
      level: 2,
      text: 'Используются средства автоматизации для выявления реальных данных в средах разработки и тестирования (возможно, покрывают не весь технологический стек).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's11.data.l3.q1',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l3',
      level: 3,
      text: 'Регламентирован жизненный цикл управления данными и требования ИБ к нему.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l3.q2',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l3',
      level: 3,
      text: 'Регламентированы правила взаимодействия с третьими сторонами. Определены типы договоров, требующих согласования со службой ИБ, а также перечень необходимых соглашений в зависимости от типов взаимодействия.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l3.q3',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l3',
      level: 3,
      text: 'Регулярно, как минимум, ежегодно, пересматривается (актуализируется) подход к категорированию информации.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l3.q4',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l3',
      level: 3,
      text: 'Перед началом взаимодействий с контрагентами выполняется анализ общедоступных данных о кибербезопасности контрагента.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l3.q5',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l3',
      level: 3,
      text: 'Для обнаружения и классификации данных «at rest» используются автоматизированные решения (например, DCAP).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l3.q6',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l3',
      level: 3,
      text: 'Используется решение класса DLP, покрыто не менее 90% пользователей и каналов взаимодействия.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's11.data.l4.q1',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l4',
      level: 4,
      text: 'Автоматизированные решения для защиты данных интегрированы с SIEM/внешним SOC.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's11.data.l4.q2',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l4',
      level: 4,
      text: 'Проводится регулярный (не реже 1 раза в год) аудит выполнения требований ИБ по жизненному циклу данных.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's11.data.l5.q1',
      sectionKey: 'data_security',
      categoryKey: 'data_security.l5',
      level: 5,
      text: 'Реестр информационных потоков обновляется ежедневно, доступен для всех авторизованных лиц.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_11_DATA_SECURITY;
