// src/surveys/v3/sections/15_incident_mgmt.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_15_INCIDENT_MGMT: Section = {
  key: 'incident_mgmt',
  title: 'Управление инцидентами ИБ',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 15,
  questions: [
    // Уровень 1
    {
      id: 's15.inc.l1.q1',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l1',
      level: 1,
      text: 'Определён (как минимум в виде рабочих документов) перечень инцидентов ИБ (или событий, классифицированных как инцидент), на которые необходимо реагировать.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l1.q2',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l1',
      level: 1,
      text: 'Все инциденты фиксируются, документируются результаты реагирования на инцидент и причины возникновения инцидента.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's15.inc.l2.q1',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l2',
      level: 2,
      text: 'Разработан план реагирования на инциденты ИБ, включающий описание этапов реагирования.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l2.q2',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l2',
      level: 2,
      text: 'Определены требования к регистрации и приоритизации инцидентов.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l2.q3',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l2',
      level: 2,
      text: 'Определены критерии инцидентов ИБ, требующих расследования.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l2.q4',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l2',
      level: 2,
      text: 'Используется автоматизированная система для регистрации инцидентов ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l2.q5',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l2',
      level: 2,
      text: 'Определён и соблюдается набор полей, необходимый для регистрации инцидентов. Информация включает в себя как минимум: статус инцидента; затрагиваемый актив; тип инцидента; приоритет/значимость.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's15.inc.l3.q1',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l3',
      level: 3,
      text: 'Процесс управления инцидентами регламентирован. Регламентированы этапы процесса, включая этап расследования.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l3.q2',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l3',
      level: 3,
      text: 'Разработаны playbook’и по реагированию на различные типы инцидентов ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l3.q3',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l3',
      level: 3,
      text: 'Используется решение класса IRP (как минимум автоматизированная локализация угроз) для управления инцидентами.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l3.q4',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l3',
      level: 3,
      text: 'Разработаны и соблюдаются SLA по реагированию на инциденты для всех участников процесса в соответствии с уровнем критичности инцидента.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's15.inc.l3.q5',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l3',
      level: 3,
      text: 'В результате расследования инцидентов формируется post-mortem и план устранения недостатков.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's15.inc.l4.q1',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l4',
      level: 4,
      text: 'Система IRP интегрирована с системой анализа и корреляции событий ИБ. Производится автоматизированная регистрация инцидентов ИБ на основе классификации.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's15.inc.l5.q1',
      sectionKey: 'incident_mgmt',
      categoryKey: 'incident_mgmt.l5',
      level: 5,
      text: 'Производится регулярное тестирование и улучшение playbook\'ов по реагированию с привлечением Red team.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_15_INCIDENT_MGMT;
