// src/surveys/v3/sections/16_security_culture.ts
import type { Section } from '../types';

const YES_NO_NA_OPTIONS = [
  { id: 'yes', label: 'Да', points: 1, weight: 1 },
  { id: 'no', label: 'Нет', points: 0, weight: 1 },
  { id: 'na', label: 'Не применимо', points: 1, weight: 0 },
] as const;

export const SECTION_16_SECURITY_CULTURE: Section = {
  key: 'security_culture',
  title: 'Культура ИБ',
  description: 'Критерии по уровням зрелости (Да/Нет/НП).',
  order: 16,
  questions: [
    // Уровень 1
    {
      id: 's16.cult.l1.q1',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l1',
      level: 1,
      text: 'Производится ознакомление работников с правилами ИБ (ВНД, ОРД, памятки) при заключении трудового договора, а также периодически.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l1.q2',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l1',
      level: 1,
      text: 'Осуществляется повышение осведомлённости работников, как минимум, в области фишинга, противодействия социальной инженерии.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 2
    {
      id: 's16.cult.l2.q1',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l2',
      level: 2,
      text: 'Организована единая точка для обращений работников компании по вопросам ИБ, набор контактов для разных каналов коммуникации и правила обращения доведены до работников компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l2.q2',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l2',
      level: 2,
      text: 'В компании проводятся регулярные киберучения. Отчёты о киберучениях предоставляются руководителю компании, по результатам киберучений принимаются решения (в т. ч. по обучению работников компании).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l2.q3',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l2',
      level: 2,
      text: 'Создана библиотека обучающих материалов, а также ВНД и РД по ИБ (база знаний), доступная всем работникам компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l2.q4',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l2',
      level: 2,
      text: 'Производится специализированное обучение по ИБ работников подразделения ИБ (возможно, не системно).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 3
    {
      id: 's16.cult.l3.q1',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Регламентирован процесс обучения и повышения осведомлённости в области ИБ, определены роли, назначены ответственные.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l3.q2',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Осуществляется повышение осведомлённости в области ИБ для клиентов компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l3.q3',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Осуществляется повышение осведомлённости в области ИБ для контрагентов, имеющих доступ в инфраструктуру компании или к данным компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l3.q4',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Используется автоматизированное решение для обучения и тестирования работников, определены критерии контроля уровня знаний.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l3.q5',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Проводятся дополнительные обучающие мероприятия для работников по результатам анализа инцидентов ИБ (как минимум подразделений ИБ и ИТ).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l3.q6',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Осуществляется регулярный пересмотр учебных материалов (не реже 1 раза в год), с учётом результатов обучения и обратной связи.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l3.q7',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Внедрена практика горизонтального обмена опытом в подразделении ИБ (практика взаимного обучения работниками ИБ).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l3.q8',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l3',
      level: 3,
      text: 'Проводится регулярная проверка уровня компетенций работников подразделения ИБ, результат учитывается при планировании обучения.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 4
    {
      id: 's16.cult.l4.q1',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l4',
      level: 4,
      text: 'Всем работникам доступны дистанционные курсы по ИБ, с функционалом выполнения упражнений, с централизованной отчётностью о результатах обучения работников компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l4.q2',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l4',
      level: 4,
      text: 'Поддержание, развитие культуры ИБ во всех процессах включено в стратегические цели компании.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l4.q3',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l4',
      level: 4,
      text: 'Внедрена практика горизонтального обмена опытом между подразделениями ИБ и ИТ (практика взаимного обучения).',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },

    // Уровень 5
    {
      id: 's16.cult.l5.q1',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l5',
      level: 5,
      text: 'Системно применяется геймификация обучения, игровые имитации реализации угроз ИБ. По результатам анализа результатов обучения ставятся задачи улучшения системы обучения ИБ компании, результаты контролируются.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
    {
      id: 's16.cult.l5.q2',
      sectionKey: 'security_culture',
      categoryKey: 'security_culture.l5',
      level: 5,
      text: 'Процесс обучения и повышения осведомлённости, учебные материалы непрерывно пересматриваются (как минимум раз в полгода) с учётом анализа результатов, обратной связи, появления новых подходов, знаний в области ИБ.',
      answerType: 'radio',
      validation: { required: true },
      options: [...YES_NO_NA_OPTIONS],
      weight: 1,
    },
  ],
};

export default SECTION_16_SECURITY_CULTURE;
